version: "3"
services:
  web:
    
    image: gotechnies/php-5.6-alpine
    ports:
       - "80:80"
       - "443:443"
    links:
       - db
       - phpmyadmin
    volumes:
      - ./:/var/www/html
    restart: always
  db:
    image: mysql:5.6
    volumes:
      - "./mysql/initial_data:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306 
    environment:
      
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    links:
     - db
    volumes:
     - /sessions
    ports:
     - 8080:80